### ISSUE TITLE
Find out why App doesn't work with gradle 3

### ISSUE THREAD

**Issue by IrosTheBeggar** [IrosTheBeggar/mstream-android-app#16]

**Comment by firekesti** [comment]
Are you using Android Studio 2.3?

**Comment by IrosTheBeggar** [comment]
Yea, I'm using AS 2.3

**Comment by IrosTheBeggar** [comment]
I also had to roll back the Android Plugin to version to 2.2.0 as well.  AS was trying to upgrade that to 2.30 which also caused problems
