### ISSUE TITLE
"Failed to decoded server response. WTF" error

### ISSUE THREAD

**Issue by ehea617** [IrosTheBeggar/mstream-android-app#56]
When trying to playback any files using mStream Express v0.6.0 and v0.3 alpha of the Android app, I get the error message "Failed to decoded server response. WTF" and "Cannot sync non-hashed files. For now..." The files I am trying to play are both MP3 and FLAC. Both filetypes result in this error.

**Comment by IrosTheBeggar** [comment]
Interesting.  I made some minor changes to the v0.6 API.  It didn't affect the web app, but I don't have any automated testing for mobile, so I missed this.

**Comment by ehea617** [comment]
Any chance of looking into this yet? It's the only thing stopping me from using mStream.

**Comment by IrosTheBeggar** [comment]
Hey @ehea617,

I'm actually looking into this now.  It's going to take some time for two reasons.  First I made an major API change a few months back to handle multi-directory configs.  And an chunk of the android code needs to changed to handle this.

Secondly, I picked up a lot of contracting work so my time is limited.  One day I hope mStream can pay enough bills that I can work on it full time.

Thanks for your patience. I wish I had a time estimate, but this open-source work is typically done at weird hours whenever I can squeeze it in

**Comment by IrosTheBeggar** [comment]
@ehea617 

i just released v0.4 that should fix these problems. Let me know if it works for you

**Comment by ehea617** [comment]
The changes do not fix the issue. The "Cannot sync non-hashed files. For now..." message has disappeared. The "Failed to decoded server response. WTF" persists. File playback does not work.

**Comment by IrosTheBeggar** [comment]
What version of android are you using?

**Comment by ehea617** [comment]
Android 7.0

**Comment by IrosTheBeggar** [comment]
Ok, this might be another API out of sync problem.  I didn't realize how old v0.6 of Express was.  Can you try the mobile app with the https://darncoyotes.mstream.io/ url?

**Comment by ehea617** [comment]
The playback works correctly with https://darncoyotes.mstream.io/ and the v0.4 Alpha version of the app.

**Comment by IrosTheBeggar** [comment]
Ok, that makes sense. The API got some modifications for security since the Express 0.6 release.  I'll release a new version of Express with the latest API once I get home today

**Comment by IrosTheBeggar** [comment]
Hmm, maybe it's a metadata call problem.  Every time a song is added to the playlist a call to the API to fetch the metadata is made?

Do you get the same problem when using the https://darncoyotes.mstream.io/  url?

**Comment by ehea617** [comment]
The message does not appear with https://darncoyotes.mstream.io/

**Comment by IrosTheBeggar** [comment]
Would it be possible for me to access your server API to see what exactly is going wrong with the metadata calls?  You can email me a link at paul.sori@gmail.com so it's not public.  You can also email me a copy of the response from the server if you don't want to share you're server URL.  

Currently error logs for Express are non-existant.  One of my next projects is to add extensive error reporting into the Express framework, but until then debugging the an Express server requires some manual work

**Comment by ehea617** [comment]
Sent you an email.

**Comment by IrosTheBeggar** [comment]
Thanks, I figured out what was wrong and released v0.8.1 of mStream Express that fixes the problem

**Comment by ehea617** [comment]
Tested with the new app version and mStream release. Works great, thanks!
