### ISSUE TITLE
Credentials Are Cleared After Closing App

### ISSUE THREAD

**Issue by ehea617** [IrosTheBeggar/mstream-android-app#58]
After logging in to an mStream Express v0.8.0 server through the v0.4 Alpha version of the app and switching to another app or closing it completely, the server credentials are erased. You have to reenter them every time you reopen the app.

**Comment by IrosTheBeggar** [comment]
I noticed this problem as well.  Will work on a fix asap

**Comment by IrosTheBeggar** [comment]
This has been fixed
